#server.servlet.context-path=/bankapp
server.port=10000

# MySQL DB Conf (commented out for SQLite testing)
#spring.datasource.url=jdbc:mysql://localhost:3306/bankappsd?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# SQLite DB Conf
spring.datasource.url=jdbc:sqlite:data.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect

# JPA & Hibernate Conf
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# JSP View Resolver Conf
spring.mvc.view.prefix:/WEB-INF/views/
spring.mvc.view.suffix:.jsp
spring.mvc.format.date= `yyyy-MM-dd`

# Logging Configuration
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR