package application.entities.nonoperational;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum District {

	ADILABAD("Adilabad"), AGAR_MALWA("Agar Malwa"), AGRA("Agra"), AHMED_NAGAR("Ahmed Nagar"), AHMEDABAD("Ahmedabad"),
	AIZAWL("Aizawl"), AJMER("Ajmer"), AKOLA("Akola"), ALAPPUZHA("Alappuzha"), ALIGARH("Aligarh"),
	ALIPURDUAR("Alipurduar"), ALIRAJPUR("Alirajpur"), ALMORA("Almora"), ALWAR("Alwar"), AMBALA("Ambala"),
	AMBEDKAR_NAGAR("Ambedkar Nagar"), AMETHI("Amethi"), AMRAVATI("Amravati"), AMRELI("Amreli"), AMRITSAR("Amritsar"),
	AMROHA("Amroha"), ANAND("Anand"), ANANTHAPUR("Ananthapur"), ANANTNAG("Anantnag"), ANGUL("Angul"), ANJAW("Anjaw"),
	ANUPPUR("Anuppur"), ARARIA("Araria"), ARIYALUR("Ariyalur"), ARVALLI("Arvalli"), ARWAL("Arwal"),
	ASHOKNAGAR("Ashoknagar"), AURAIYA("Auraiya"), AURANGABAD("Aurangabad"), AURANGABADBH("Aurangabadbh"),
	AYODHYA("Ayodhya"), AZAMGARH("Azamgarh"), BAGALKOT("Bagalkot"), BAGESHWAR("Bageshwar"), BAGPAT("Bagpat"),
	BAHRAICH("Bahraich"), BAKSA("Baksa"), BALAGHAT("Balaghat"), BALANGIR("Balangir"), BALESWAR("Baleswar"),
	BALLARI_BELLARY("Ballari Bellary"), BALLIA("Ballia"), BALOD("Balod"), BALODA_BAZAR("Baloda Bazar"),
	BALRAMPUR_CG("Balrampur (CG)"), BALRAMPUR_UP("Balrampur (UP)"), BANASKANTHA("Banaskantha"), BANDA("Banda"),
	BANDIPORE("Bandipore"), BANKA("Banka"), BANKURA("Bankura"), BANKURA_DISTRICT_FOREST("Bankura District Forest"),
	BANSWARA("Banswara"), BARABANKI("Barabanki"), BARAMULLA("Baramulla"), BARAN("Baran"), BAREILLY("Bareilly"),
	BARGARH("Bargarh"), BARMER("Barmer"), BARNALA("Barnala"), BARPETA("Barpeta"), BARWANI("Barwani"), BASTAR("Bastar"),
	BASTI("Basti"), BATHINDA("Bathinda"), BEED("Beed"), BEGUSARAI("Begusarai"), BELAGAVI("Belagavi"),
	BEMETARA("Bemetara"), BANGALORE_RURAL("Bangalore Rural"), BANGALORE_URBAN("Bangalore Urban"), BETUL("Betul"),
	BHADOHI("Bhadohi"), BHADRADRI_KOTHAGUDEM("Bhadradri Kothagudem"), BHADRAK("Bhadrak"), BHAGALPUR("Bhagalpur"),
	BHANDARA("Bhandara"), BHARATPUR("Bharatpur"), BHARUCH("Bharuch"), BHAVNAGAR("Bhavnagar"), BHILWARA("Bhilwara"),
	BHIND("Bhind"), BHIWANI("Bhiwani"), BHOJPUR("Bhojpur"), BHOPAL("Bhopal"), BIDAR("Bidar"), BIJAPUR("Bijapur"),
	BIJNOR("Bijnor"), BIKANER("Bikaner"), BILASPUR("Bilaspur"), BILASPUR_HP("Bilaspur Hp"), BIRBHUM("Birbhum"),
	BISHNUPUR("Bishnupur"), BISWANATH("Biswanath"), BOKARO("Bokaro"), BONGAIGAON("Bongaigaon"), BOTAD("Botad"),
	BOUDH("Boudh"), BUDAUN("Budaun"), BUDGAM("Budgam"), BULANDSHAHR("Bulandshahr"), BULDHANA("Buldhana"),
	BUNDI("Bundi"), BURHANPUR("Burhanpur"), BUXAR("Buxar"), CACHAR("Cachar"), ITANAGAR("Itanagar"),
	CENTRAL_DELHI("Central Delhi"), CHAMBA("Chamba"), CHAMOLI("Chamoli"), CHAMPAWAT("Champawat"), CHAMPHAI("Champhai"),
	CHAMRAJNAGAR("Chamrajnagar"), CHANDAULI("Chandauli"), CHANDEL("Chandel"), CHANDIGARH("Chandigarh"),
	CHANDRAPUR("Chandrapur"), CHANGLANG("Changlang"), CHARAIDEO("Charaideo"), CHARKHI_DADRI("Charkhi Dadri"),
	CHATRA("Chatra"), CHENGALPATTU("Chengalpattu"), CHENNAI("Chennai"), CHHATARPUR("Chhatarpur"),
	CHHINDWARA("Chhindwara"), CHHOTAUDEPUR("Chhotaudepur"), CHIKKABALLAPUR("Chikkaballapur"),
	CHIKKAMAGALURU("Chikkamagaluru"), CHIRANG("Chirang"), CHITRADURGA("Chitradurga"), CHITRAKOOT("Chitrakoot"),
	CHITTOOR("Chittoor"), CHITTORGARH("Chittorgarh"), CHURACHANDPUR("Churachandpur"), CHURU("Churu"),
	COIMBATORE("Coimbatore"), COOCH_BEHAR("Cooch Behar"), CUDDALORE("Cuddalore"), CUDDAPAH("Cuddapah"),
	CUTTACK("Cuttack"), DADRA_NAGAR_HAVELI("Dadra Nagar Haveli"), DAHOD("Dahod"), DAKSHINA_KANNADA("Dakshina Kannada"),
	DAMAN("Daman"), DAMOH("Damoh"), DANTEWADA("Dantewada"), DARBHANGA("Darbhanga"), DARJEELING("Darjeeling"),
	DARRANG("Darrang"), DATIA("Datia"), DAUSA("Dausa"), DAVANGERE("Davangere"), DEHRADUN("Dehradun"),
	DEOGARH("Deogarh"), DEOGHAR("Deoghar"), DEORIA("Deoria"), DEVBHUMI_DWARKA("Devbhumi Dwarka"), DEWAS("Dewas"),
	DHALAI("Dhalai"), DHAMTARI("Dhamtari"), DHANBAD("Dhanbad"), DHAR("Dhar"), DHARMAPURI("Dharmapuri"),
	DHARWAD("Dharwad"), DHEMAJI("Dhemaji"), DHENKANAL("Dhenkanal"), DHOLPUR("Dholpur"), DHUBRI("Dhubri"),
	DHULE("Dhule"), DIBANG_VALLEY("Dibang Valley"), DIBRUGARH("Dibrugarh"),
	DIMA_HASAO("Dima Hasao (North Cachar Hills)"), DIMAPUR("Dimapur"), DINDIGUL("Dindigul"), DINDORI("Dindori"),
	DIU("Diu"), DODA("Doda"), DUMKA("Dumka"), DUNGARPUR("Dungarpur"), DURG("Durg"), EAST_CHAMPARAN("East Champaran"),
	EAST_DELHI("East Delhi"), EAST_GARO_HILLS("East Garo Hills"), EAST_GODAVARI("East Godavari"),
	EAST_JAINTIA_HILLS("East Jaintia Hills"), EAST_KAMENG("East Kameng"), EAST_KHASI_HILLS("East Khasi Hills"),
	EAST_SIANG("East Siang"), EAST_SIKKIM("East Sikkim"), EAST_SINGHBHUM("East Singhbhum"), ERNAKULAM("Ernakulam"),
	ERODE("Erode"), ETAH("Etah"), ETAWAH("Etawah"), FAIZABAD("Faizabad"), FARIDABAD("Faridabad"), FARIDKOT("Faridkot"),
	FARRUKHABAD("Farrukhabad"), FATEHABAD("Fatehabad"), FATEHGARH_SAHIB("Fatehgarh Sahib"), FATEHPUR("Fatehpur"),
	FAZILKA("Fazilka"), FEROZEPUR("Ferozepur"), FIROZABAD("Firozabad"), GADAG("Gadag"), GADCHIROLI("Gadchiroli"),
	GAJAPATI("Gajapati"), GANDERBAL("Ganderbal"), GANDHINAGAR("Gandhinagar"), GANJAM("Ganjam"), GARHWA("Garhwa"),
	GARIABAND("Gariaband"), GAUTAM_BUDDHA_NAGAR("Gautam Buddha Nagar"), GAYA("Gaya"), GHAZIABAD("Ghaziabad"),
	GHAZIPUR("Ghazipur"), GIR_SOMNATH("Gir Somnath"), GIRIDIH("Giridih"), GOALPARA("Goalpara"), GODDA("Godda"),
	GOLAGHAT("Golaghat"), GOMATI("Gomati"), GONDA("Gonda"), GONDIA("Gondia"), GOPALGANJ("Gopalganj"),
	GORAKHPUR("Gorakhpur"), GUMLA("Gumla"), GUNA("Guna"), GUNTUR("Guntur"), GURDASPUR("Gurdaspur"),
	GURUGRAM("Gurugram"), GWALIOR("Gwalior"), HAILAKANDI("Hailakandi"), HAMIRPUR("Hamirpur"),
	HAMIRPUR_HP("Hamirpur (HP)"), HANUMANGARH("Hanumangarh"), HAPUR("Hapur"), HARDA("Harda"), HARDOI("Hardoi"),
	HARIDWAR("Haridwar"), HASSAN("Hassan"), HATHRAS("Hathras"), HAVERI("Haveri"), HAZARIBAG("Hazaribag"),
	HINGOLI("Hingoli"), HISAR("Hisar"), HOJAI("Hojai"), HOOGHLY("Hooghly"), HOSHANGABAD("Hoshangabad"),
	HOSHIARPUR("Hoshiarpur"), HOWRAH("Howrah"), HYDERABAD("Hyderabad"), IDUKKI("Idukki"), IMPHAL_EAST("Imphal East"),
	IMPHAL_WEST("Imphal West"), INDORE("Indore"), JABALPUR("Jabalpur"), JAGATSINGHAPUR("Jagatsinghapur"),
	JAGTIAL("Jagtial"), JAIPUR("Jaipur"), JAISALMER("Jaisalmer"), JAJPUR("Jajpur"), JALANDHAR("Jalandhar"),
	JALAUN("Jalaun"), JALGAON("Jalgaon"), JALNA("Jalna"), JALORE("Jalore"), JALPAIGURI("Jalpaiguri"), JAMMU("Jammu"),
	JAMNAGAR("Jamnagar"), JAMTARA("Jamtara"), JAMUI("Jamui"), JANGAON("Jangaon"), JANJGIR_CHAMPA("Janjgir-Champa"),
	JASHPUR("Jashpur"), JAUNPUR("Jaunpur"), JAYASHANKAR_BHOOPALPALLY("Jayashankar Bhoopalpally"),
	JEHANABAD("Jehanabad"), JHABUA("Jhabua"), JHAJJAR("Jhajjar"), JHALAWAR("Jhalawar"), JHANSI("Jhansi"),
	JHARGRAM("Jhargram"), JHARSUGUDA("Jharsuguda"), JHUNJHUNU("Jhunjhunu"), JIND("Jind"), JIRIBAM("Jiribam"),
	JODHPUR("Jodhpur"), JOGULAMBA_GADWAL("Jogulamba Gadwal"), JORHAT("Jorhat"), JUNAGADH("Junagadh"),
	KABIRDHAM_KAWARDHA("Kabirdham Kawardha"), KACHCHH("Kachchh"), KAIMUR_BHABUA("Kaimur Bhabua"), KAITHAL("Kaithal"),
	KAKCHING("Kakching"), KALABURAGI("Kalaburagi"), KALAHANDI("Kalahandi"), KALIMPONG("Kalimpong"),
	KALLAKURICHI("Kallakurichi"), KAMAREDDY("Kamareddy"), KAMJONG("Kamjong"), KAMLE("Kamle"), KAMRUP("Kamrup"),
	KAMRUP_METROPOLITAN("Kamrup Metropolitan"), KANCHIPURAM("Kanchipuram"), KANDHAMAL("Kandhamal"),
	KANGPOKPI("Kangpokpi"), KANGRA("Kangra"), KANKER("Kanker"), KANNAUJ("Kannauj"), KANNUR("Kannur"),
	KANPUR_DEHAT("Kanpur Dehat"), KANPUR_NAGAR("Kanpur Nagar"), KANYAKUMARI("Kanyakumari"), KAPURTHALA("Kapurthala"),
	KARAIKAL("Karaikal"), KARAULI("Karauli"), KARBI_ANGLONG("Karbi Anglong"), KARGIL("Kargil"), KARIMGANJ("Karimganj"),
	KARIMNAGAR("Karimnagar"), KARNAL("Karnal"), KARUR("Karur"), KASARGOD("Kasargod"), KASGANJ("Kasganj"),
	KATHUA("Kathua"), KATIHAR("Katihar"), KATNI("Katni"), KAUSHAMBI("Kaushambi"), KENDRAPARA("Kendrapara"),
	KENDUJHAR("Kendujhar"), KHAGARIA("Khagaria"), KHAMMAM("Khammam"), KHANDWA("Khandwa"), KHARGONE("Khargone"),
	KHEDA("Kheda"), KHORDHA("Khordha"), KHOWAI("Khowai"), KHUNTI("Khunti"), KINNAUR("Kinnaur"), KIPHIRE("Kiphire"),
	KISHANGANJ("Kishanganj"), KISHTWAR("Kishtwar"), KODAGU("Kodagu"), KODERMA("Koderma"), KOHIMA("Kohima"),
	KOKRAJHAR("Kokrajhar"), KOLAR("Kolar"), KOLASIB("Kolasib"), KOLHAPUR("Kolhapur"), KOLKATA("Kolkata"),
	KOLLAM("Kollam"), KONDAGAON("Kondagaon"), KOPPAL("Koppal"), KORAPUT("Koraput"), KORBA("Korba"),
	KOREA_KORIYA("Korea Koriya"), KOTA("Kota"), KOTTAYAM("Kottayam"), KOZHIKODE("Kozhikode"), KRA_DAADI("Kra Daadi"),
	KRISHNA("Krishna"), KRISHNAGIRI("Krishnagiri"), KULGAM("Kulgam"), KULLU("Kullu"), KUMURAM_BHEEM("Kumuram Bheem"),
	KUPWARA("Kupwara"), KURNOOL("Kurnool"), KURUKSHETRA("Kurukshetra"), KURUNG_KUMEY("Kurung Kumey"),
	KUSHINAGAR("Kushinagar"), LAHUL_AND_SPITI("Lahul And Spiti"), LAKHIMPUR("Lakhimpur"),
	LAKHIMPUR_KHERI("Lakhimpur Kheri"), LAKHISARAI("Lakhisarai"), LAKSHADWEEP("Lakshadweep"), LALITPUR("Lalitpur"),
	LATEHAR("Latehar"), LATUR("Latur"), LAWNGTLAI("Lawngtlai"), LEH("Leh"), LEPA_RADA("Lepa Rada"),
	LOHARDAGA("Lohardaga"), LOHIT("Lohit"), LONGDING("Longding"), LONGLENG("Longleng"),
	LOWER_DIBANG_VALLEY("Lower Dibang Valley"), LOWER_SIANG("Lower Siang"), LOWER_SUBANSIRI("Lower Subansiri"),
	LUCKNOW("Lucknow"), LUDHIANA("Ludhiana"), LUNGLEI("Lunglei"), MADHEPURA("Madhepura"), MADHUBANI("Madhubani"),
	MADURAI("Madurai"), MAHABUB_NAGAR("Mahabub Nagar"), MAHABUBABAD("Mahabubabad"), MAHARAJGANJ("Maharajganj"),
	MAHASAMUND("Mahasamund"), MAHE("Mahe"), MAHENDRAGARH("Mahendragarh"), MAHESANA("Mahesana"), MAHISAGAR("Mahisagar"),
	MAHOBA("Mahoba"), MAINPURI("Mainpuri"), MAJULI("Majuli"), MALAPPURAM("Malappuram"), MALDA("Malda"),
	MALKANGIRI("Malkangiri"), MAMMIT("Mammit"), MANCHERIAL("Mancherial"), MANDI("Mandi"), MANDLA("Mandla"),
	MANDSAUR("Mandsaur"), MANDYA("Mandya"), MANSA("Mansa"), MATHURA("Mathura"), MAU("Mau"),
	MAYILADUTHURAI("Mayiladuthurai"), MAYURBHANJ("Mayurbhanj"), MEDAK("Medak"),
	MEDCHAL_MALKAJGIRI("Medchal-Malkajgiri"), MEERUT("Meerut"), MIRZAPUR("Mirzapur"), MOGA("Moga"), MOHALI("Mohali"),
	MOKOKCHUNG("Mokokchung"), MON("Mon"), MORADABAD("Moradabad"), MORBI("Morbi"), MORENA("Morena"),
	MORIGAON("Morigaon"), MUKTSAR("Muktsar"), MUMBAI("Mumbai"), MUMBAI_SUBURBAN("Mumbai Suburban"), MUNGELI("Mungeli"),
	MUNGER("Munger"), MURSHIDABAD("Murshidabad"), MUZAFFARNAGAR("Muzaffarnagar"), MUZAFFARPUR("Muzaffarpur"),
	MYSURU("Mysuru"), NABARANGAPUR("Nabarangapur"), NADIA("Nadia"), NAGAON("Nagaon"), NAGAPATTINAM("Nagapattinam"),
	NAGARKURNOOL("Nagarkurnool"), NAGAUR("Nagaur"), NAGPUR("Nagpur"), NAINITAL("Nainital"), NALANDA("Nalanda"),
	NALBARI("Nalbari"), NALGONDA("Nalgonda"), NAMAKKAL("Namakkal"), NAMSAI("Namsai"), NANDED("Nanded"),
	NANDURBAR("Nandurbar"), NARAYANPET("Narayanpet"), NARAYANPUR("Narayanpur"), NARMADA("Narmada"),
	NARSINGHPUR("Narsinghpur"), NASHIK("Nashik"), NAVSARI("Navsari"), NAWADA("Nawada"), NAWANSHAHR("Nawanshahr"),
	NAYAGARH("Nayagarh"), NEEMUCH("Neemuch"), NELLORE("Nellore"), NEW_DELHI("New Delhi"), NICOBAR("Nicobar"),
	NILGIRIS("Nilgiris"), NIRMAL("Nirmal"), NIWARI("Niwari"), NIZAMABAD("Nizamabad"), NOKLAK("Noklak"), NONEY("Noney"),
	NORTH_24_PARGANAS("North 24 Parganas"), NORTH_MIDDLE_ANDAMAN("North Middle Andaman"),
	NORTH_DISTRICT("North District"), NORTH_EAST_DELHI("North East Delhi"), NORTH_GARO_HILLS("North Garo Hills"),
	NORTH_GOA("North Goa"), NORTH_SIKKIM("North Sikkim"), NORTH_TRIPURA("North Tripura"),
	NORTH_WEST_DELHI("North West Delhi"), NUAPADA("Nuapada"), NUH("Nuh"), OSMANABAD("Osmanabad"),
	PAKKE_KESSANG("Pakke Kessang"), PAKUR("Pakur"), PALAKKAD("Palakkad"), PALAMAU("Palamau"), PALGHAR("Palghar"),
	PALI("Pali"), PALWAL("Palwal"), PANCH_MAHALS("Panch Mahals"), PANCHKULA("Panchkula"), PANIPAT("Panipat"),
	PANNA("Panna"), PAPUM_PARE("Papum Pare"), PARBHANI("Parbhani"), WEST_MEDINIPUR("West Medinipur"),
	WEST_BARDHAMAN("West Bardhaman"), PATAN("Patan"), PATHANAMTHITTA("Pathanamthitta"), PATHANKOT("Pathankot"),
	PATIALA("Patiala"), PATNA("Patna"), PAURI_GARHWAL("Pauri Garhwal"), PEDDAPALLY("Peddapally"),
	PERAMBALUR("Perambalur"), PEREN("Peren"), PHEK("Phek"), PHERZAWL("Pherzawl"), PILIBHIT("Pilibhit"),
	PITHORAGARH("Pithoragarh"), PONDICHERRY("Pondicherry"), POONCH("Poonch"), PORBANDAR("Porbandar"),
	PRAKASAM("Prakasam"), PRATAPGARH_RJ("Pratapgarh (RJ)"), PRATAPGARH_UP("Pratapgarh (UP)"), PRAYAGRAJ("Prayagraj"),
	PUDUKKOTTAI("Pudukkottai"), PULWAMA("Pulwama"), PUNE("Pune"), PURBA_BURDWAN_BARDHAMAN("Purba Burdwan Bardhaman"),
	PURBA_MEDINIPUR_EAST_MEDINIPUR("Purba Medinipur East Medinipur"), PURI("Puri"), PURNIA("Purnia"),
	PURULIA("Purulia"), PURULIA_DISTRICT_POLICE("Purulia District Police"), RAEBARELI("Raebareli"), RAICHUR("Raichur"),
	RAIGARH("Raigarh"), RAIGARHMH("Raigarhmh"), RAIPUR("Raipur"), RAISEN("Raisen"),
	RAJANNA_SIRCILLA("Rajanna Sircilla"), RAJAURI("Rajauri"), RAJGARH("Rajgarh"), RAJKOT("Rajkot"),
	RAJNANDGAON("Rajnandgaon"), RAJSAMAND("Rajsamand"), RAMANAGAR("Ramanagar"), RAMANATHAPURAM("Ramanathapuram"),
	RAMBAN("Ramban"), RAMGARH("Ramgarh"), RAMPUR("Rampur"), RANCHI("Ranchi"), RANGAREDDY("Rangareddy"),
	RANIPET("Ranipet"), RATLAM("Ratlam"), RATNAGIRI("Ratnagiri"), RAYAGADA("Rayagada"), REASI("Reasi"), REWA("Rewa"),
	REWARI("Rewari"), RI_BHOI("Ri Bhoi"), ROHTAK("Rohtak"), ROHTAS("Rohtas"), RUDRAPRAYAG("Rudraprayag"),
	RUPNAGAR("Rupnagar"), SABARKANTHA("Sabarkantha"), SAGAR("Sagar"), SAHARANPUR("Saharanpur"), SAHARSA("Saharsa"),
	SAHIBGANJ("Sahibganj"), SAIHA("Saiha"), SALEM("Salem"), SAMASTIPUR("Samastipur"), SAMBA("Samba"),
	SAMBALPUR("Sambalpur"), SAMBHAL("Sambhal"), SANGAREDDY("Sangareddy"), SANGLI("Sangli"), SANGRUR("Sangrur"),
	SANT_KABIR_NAGAR("Sant Kabir Nagar"), SARAN("Saran"), SATARA("Satara"), SATNA("Satna"),
	SAWAI_MADHOPUR("Sawai Madhopur"), SEHORE("Sehore"), SENAPATI("Senapati"), SEONI("Seoni"), SEPAHIJALA("Sepahijala"),
	SERAIKELA_KHARSAWAN("Seraikela_kharsawan"), SERCHHIP("Serchhip"), SHAHDARA("Shahdara"), SHAHDOL("Shahdol"),
	SHAHJAHANPUR("Shahjahanpur"), SHAJAPUR("Shajapur"), SHAMLI("Shamli"), SHEIKHPURA("Sheikhpura"), SHEOHAR("Sheohar"),
	SHEOPUR("Sheopur"), SHI_YOMI("Shi Yomi"), SHIMLA("Shimla"), SHIVAMOGGA("Shivamogga"), SHIVPURI("Shivpuri"),
	SHOPIAN_DISTRICT("Shopian District"), SHRAWASTI("Shrawasti"), SIANG("Siang"), SIDDHARTHNAGAR("Siddharthnagar"),
	SIDDIPET("Siddipet"), SIDHI("Sidhi"), SIKAR("Sikar"), SIMDEGA("Simdega"), SINDHUDURG("Sindhudurg"),
	SINGRAULI("Singrauli"), SIRMAUR("Sirmaur"), SIROHI("Sirohi"), SIRSA("Sirsa"), SITAMARHI("Sitamarhi"),
	SITAPUR("Sitapur"), SIVAGANGA("Sivaganga"), SIVASAGAR("Sivasagar"), SIWAN("Siwan"), SOLAN("Solan"),
	SOLAPUR("Solapur"), SONAPUR("Sonapur"), SONBHADRA("Sonbhadra"), SONIPAT("Sonipat"), SONITPUR("Sonitpur"),
	SOUTH_24_PARGANAS("South 24 Parganas"), SOUTH_ANDAMAN("South Andaman"), SOUTH_DELHI("South Delhi"),
	SOUTH_DINAJPUR("South Dinajpur"), SOUTH_EAST_DELHI("South East Delhi"), SOUTH_GARO_HILLS("South Garo Hills"),
	SOUTH_GOA("South Goa"), SOUTH_SALAMARA_MANKACHAR("South Salamara_mankachar"), SOUTH_SIKKIM("South Sikkim"),
	SOUTH_TRIPURA("South Tripura"), SOUTH_WEST_DELHI("South West Delhi"),
	SOUTH_WEST_GARO_HILLS("South West Garo Hills"), SOUTH_WEST_KHASI_HILLS("South West Khasi Hills"),
	SRI_GANGANAGAR("Sri Ganganagar"), SRIKAKULAM("Srikakulam"), SRINAGAR("Srinagar"), SUKMA("Sukma"),
	SULTANPUR("Sultanpur"), SUNDERGARH("Sundergarh"), SUPAUL("Supaul"), SURAJPUR("Surajpur"), SURAT("Surat"),
	SURENDRA_NAGAR("Surendra Nagar"), SURGUJA("Surguja"), SURYAPET("Suryapet"), TAMENGLONG("Tamenglong"), TAPI("Tapi"),
	TARN_TARAN("Tarn Taran"), TAWANG("Tawang"), TEHRI_GARHWAL("Tehri Garhwal"), TENGNOUPAL("Tengnoupal"),
	TENKASI("Tenkasi"), THANE("Thane"), THANJAVUR("Thanjavur"), THE_DANGS("The Dangs"), THENI("Theni"),
	THIRUVANANTHAPURAM("Thiruvananthapuram"), THOUBAL("Thoubal"), THRISSUR("Thrissur"), TIKAMGARH("Tikamgarh"),
	TINSUKIA("Tinsukia"), TIRAP("Tirap"), TIRUCHIRAPPALLI("Tiruchirappalli"), TIRUNELVELI("Tirunelveli"),
	TIRUPATHUR("Tirupathur"), TIRUPPUR("Tiruppur"), TIRUVALLUR("Tiruvallur"), TIRUVANNAMALAI("Tiruvannamalai"),
	TIRUVARUR("Tiruvarur"), TONK("Tonk"), TUENSANG("Tuensang"), TUMAKURU("Tumakuru"), TUTICORIN("Tuticorin"),
	UDAIPUR("Udaipur"), UDALGURI("Udalguri"), UDHAM_SINGH_NAGAR("Udham Singh Nagar"), UDHAMPUR("Udhampur"),
	UDUPI("Udupi"), UJJAIN("Ujjain"), UKHRUL("Ukhrul"), UMARIA("Umaria"), UNA("Una"), UNAKOTI("Unakoti"),
	UNNAO("Unnao"), UPPER_SIANG("Upper Siang"), UPPER_SUBANSIRI("Upper Subansiri"),
	UTTAR_DINAJPUR_NORTH_DINAJPUR("Uttar Dinajpur North Dinajpur"), UTTARA_KANNADA_KARWAR("Uttara Kannada Karwar"),
	UTTARKASHI("Uttarkashi"), VADODARA("Vadodara"), VAISHALI("Vaishali"), VALSAD("Valsad"), VARANASI("Varanasi"),
	VELLORE("Vellore"), VIDISHA("Vidisha"), VIKARABAD("Vikarabad"), VILLUPURAM("Villupuram"),
	VIRUDHUNAGAR("Virudhunagar"), VISAKHAPATNAM("Visakhapatnam"), VIZIANAGARAM("Vizianagaram"),
	WANAPARTHY("Wanaparthy"), WARANGAL_JAYASHANKAR_BHOOPALPALLY("Warangal Jayashankar Bhoopalpally"),
	WARANGAL_MULUGU("Warangal Mulugu"), WARANGAL_RURAL("Warangal Rural"), WARANGAL_URBAN("Warangal Urban"),
	WARDHA("Wardha"), WASHIM("Washim"), WAYANAD("Wayanad"), WEST_CHAMPARAN("West Champaran"), WEST_DELHI("West Delhi"),
	WEST_GARO_HILLS("West Garo Hills"), WEST_GODAVARI("West Godavari"), WEST_JAINTIA_HILLS("West Jaintia Hills"),
	WEST_KAMENG("West Kameng"), WEST_KARBI_ANGLONG("West Karbi Anglong"), WEST_KHASI_HILLS("West Khasi Hills"),
	WEST_SIANG("West Siang"), WEST_SIKKIM("West Sikkim"), WEST_SINGHBHUM("West Singhbhum"),
	WEST_TRIPURA("West Tripura"), WOKHA("Wokha"), YADADRI_BHUVANAGIRI("Yadadri Bhuvanagiri"), YADGIR("Yadgir"),
	YAMUNA_NAGAR("Yamuna Nagar"), YANAM("Yanam"), YAVATMAL("Yavatmal"), ZUNHEBOTO("Zunheboto");

	private final String district;

	private District() {
		this.district = "";
	}
	
	
}
